name: Push a new tag with Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Detect template version
        uses: ShotaKitazawa/action-detect-version@main
        id: detect-version
        if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'update-template') }}
        env:
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
        with:
          dir: ./templates

      - name: Get sentence of Release Note from Pull Request
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        if: ${{ steps.bump-semver.outputs.new_version != null }}
        with:
          text: ${{ steps.get-merged-pull-request.outputs.body }}
          regex: '```release_note([\s\S]*)```'

      - name: Push Tag
        uses: actions-ecosystem/action-push-tag@v1
        id: push-tag
        if: ${{ steps.detect-version.outputs.new_version != null }}
        with:
          tag: ${{ steps.detect-version.outputs.new_version }}

      - name: Create Release
        uses: actions/create-release@v1
        id: create-release
        if: ${{ steps.detect-version.outputs.new_version != null }}
        with:
          tag_name: ${{ steps.detect-version.outputs.new_version }}
          release_name: ${{ steps.detect-version.outputs.new_version }}
          body: ${{ steps.regex-match.outputs.group1 }}
          draft: false
          prerelease: false

